name: Build AndUEDumper

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: true

    - name: Run Project Build Script
      run: |
        cd AndUEDumper
        chmod +x build.sh
        export ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        ./build.sh

    - name: Upload Built Binary
      uses: actions/upload-artifact@v4
      with:
        name: AndUEDumper-Binaries
        path: |
          AndUEDumper/out/
